/**
 * Writes src/data/eventsSnapshot.generated.ts from the Meetup iCal feed.
 *
 * The snapshot is what crawlers and link unfurlers see: scripts/prerender.mjs
 * bakes it, and its Event JSON-LD, into the served HTML. Visitors get the live
 * list from /api/events instead, so the snapshot only has to be recent, not
 * current.
 *
 * Runs as part of `pnpm build`. On any failure it warns and leaves the
 * committed snapshot alone — a build must never fail, and must never ship an
 * empty events section, because Meetup was unreachable.
 *
 * Imports the parser with an explicit .ts extension: Node strips its types but
 * does not guess extensions the way the bundler's resolver does.
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseIcal } from '../src/lib/parseIcal.ts';

const FEED_URL = 'https://www.meetup.com/stanislaus-humanists/events/ical/';
const TIMEOUT_MS = 10_000;

const appRoot = path.resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const outputPath = path.join(appRoot, 'src', 'data', 'eventsSnapshot.generated.ts');

function render(events, generatedAt) {
  return `// Generated by scripts/generate-events.mjs from the Meetup iCal feed.
// Do not edit. Venue data is hand-maintained in eventLocations.ts.
//
// This is the crawler-facing snapshot, committed so a build still has events
// when the feed is unreachable. The live list comes from /api/events.
import type { HumanistEvent } from '../lib/parseIcal';

export const generatedAt = '${generatedAt}';

export const eventsSnapshot: HumanistEvent[] = ${JSON.stringify(events, null, 2)};
`;
}

async function main() {
  const response = await fetch(FEED_URL, {
    signal: AbortSignal.timeout(TIMEOUT_MS),
    headers: { accept: 'text/calendar' },
  });

  if (!response.ok) {
    throw new Error(`Feed returned HTTP ${response.status}`);
  }

  const events = parseIcal(await response.text());

  // A feed that parses to nothing is more likely a changed format than a group
  // with no events planned. Keep the committed snapshot rather than blanking
  // the section on every crawler that visits before the next deploy.
  if (events.length === 0) {
    throw new Error('Feed parsed to zero upcoming events');
  }

  await writeFile(outputPath, render(events, new Date().toISOString()), 'utf8');
  console.log(`generate-events: wrote ${events.length} events to ${path.relative(appRoot, outputPath)}`);
}

try {
  await main();
} catch (error) {
  console.warn(
    `generate-events: keeping the committed snapshot — ${error instanceof Error ? error.message : error}`,
  );
}
