// Generated by scripts/generate-events.mjs from the Meetup iCal feed.
// Do not edit. Venue data is hand-maintained in eventLocations.ts.
//
// This is the crawler-facing snapshot, committed so a build still has events
// when the feed is unreachable. The live list comes from /api/events.
import type { HumanistEvent } from '../lib/parseIcal';

export const generatedAt = '2026-08-23T22:17:12.447Z';

export const eventsSnapshot: HumanistEvent[] = [
  {
    "id": "event_315836966",
    "title": "Queen Bean Coffee Klatch (2nd Sunday)",
    "date": "2026-09-13",
    "time": "10:00 AM",
    "startsAt": "2026-09-13T10:00:00-07:00",
    "endsAt": "2026-09-13T12:00:00-07:00",
    "description": "Stanislaus Humanists\nSecond Sunday of the month. Bring books, devices, or notepads while we solve the world's problems, exchange witty repartee, and drink delicious coffee.",
    "url": "https://www.meetup.com/stanislaus-humanists/events/315836966/"
  },
  {
    "id": "event_dnghztyjcmbjc",
    "title": "Game Night",
    "date": "2026-09-26",
    "time": "5:00 PM",
    "startsAt": "2026-09-26T17:00:00-07:00",
    "endsAt": "2026-09-26T21:00:00-07:00",
    "description": "Stanislaus Humanists\nCome and play some games with us! We will have a variety of games to choose from. It will be at Roundtable Pizza in Riverbank.",
    "url": "https://www.meetup.com/stanislaus-humanists/events/dnghztyjcmbjc/"
  },
  {
    "id": "event_316222488",
    "title": "Queen Bean Coffee Klatch (2nd Sunday)",
    "date": "2026-10-11",
    "time": "10:00 AM",
    "startsAt": "2026-10-11T10:00:00-07:00",
    "endsAt": "2026-10-11T12:00:00-07:00",
    "description": "Stanislaus Humanists\nSecond Sunday of the month. Bring books, devices, or notepads while we solve the world's problems, exchange witty repartee, and drink delicious coffee.",
    "url": "https://www.meetup.com/stanislaus-humanists/events/316222488/"
  },
  {
    "id": "event_dnghztyjcnbgc",
    "title": "Game Night",
    "date": "2026-10-24",
    "time": "5:00 PM",
    "startsAt": "2026-10-24T17:00:00-07:00",
    "endsAt": "2026-10-24T21:00:00-07:00",
    "description": "Stanislaus Humanists\nCome and play some games with us! We will have a variety of games to choose from. It will be at Roundtable Pizza in Riverbank.",
    "url": "https://www.meetup.com/stanislaus-humanists/events/dnghztyjcnbgc/"
  },
  {
    "id": "event_qbjkvtyjcpblb",
    "title": "Queen Bean Coffee Klatch (2nd Sunday)",
    "date": "2026-11-08",
    "time": "10:00 AM",
    "startsAt": "2026-11-08T10:00:00-08:00",
    "endsAt": "2026-11-08T12:00:00-08:00",
    "description": "Stanislaus Humanists\nSecond Sunday of the month. Bring books, devices, or notepads while we solve the world's problems, exchange witty repartee, and drink delicious coffee.",
    "url": "https://www.meetup.com/stanislaus-humanists/events/qbjkvtyjcpblb/"
  },
  {
    "id": "event_dnghztyjcpblc",
    "title": "Game Night",
    "date": "2026-11-28",
    "time": "5:00 PM",
    "startsAt": "2026-11-28T17:00:00-08:00",
    "endsAt": "2026-11-28T21:00:00-08:00",
    "description": "Stanislaus Humanists\nCome and play some games with us! We will have a variety of games to choose from. It will be at Roundtable Pizza in Riverbank.",
    "url": "https://www.meetup.com/stanislaus-humanists/events/dnghztyjcpblc/"
  },
  {
    "id": "event_qbjkvtyjcqbrb",
    "title": "Queen Bean Coffee Klatch (2nd Sunday)",
    "date": "2026-12-13",
    "time": "10:00 AM",
    "startsAt": "2026-12-13T10:00:00-08:00",
    "endsAt": "2026-12-13T12:00:00-08:00",
    "description": "Stanislaus Humanists\nSecond Sunday of the month. Bring books, devices, or notepads while we solve the world's problems, exchange witty repartee, and drink delicious coffee.",
    "url": "https://www.meetup.com/stanislaus-humanists/events/qbjkvtyjcqbrb/"
  },
  {
    "id": "event_dnghztyjcqbjc",
    "title": "Game Night",
    "date": "2026-12-26",
    "time": "5:00 PM",
    "startsAt": "2026-12-26T17:00:00-08:00",
    "endsAt": "2026-12-26T21:00:00-08:00",
    "description": "Stanislaus Humanists\nCome and play some games with us! We will have a variety of games to choose from. It will be at Roundtable Pizza in Riverbank.",
    "url": "https://www.meetup.com/stanislaus-humanists/events/dnghztyjcqbjc/"
  }
];
